MOHConfig = {
    "headers": {
        "MANDATORY_FIELDS": "mandatory fields",
        "SAMPLE_TYPE": "sample type",
        "SAMPLE_NAME": "sample name, pool name or existing lims id",
        "SAMPLE_SET": "sample set",
        "INDIVIDUAL_ID": "individual id",
        "COHORT_ID": "cohort id",
        "CONTAINER_TYPE": "container type",
        "CONTAINER_NAME": "container name",
        "WELL": "well",
        "CONTAINER_BARCODE": "container barcode",
        "TUBE_CARRIER_TYPE": "tube carrier type",
        "TYPE_CARRIER_NAME": "tube carrier name",
        "TUBE_CARRIER_BARCODE": "tube carrier barcode",
        "SPECIES": "species",
        "GENOME_SIZE": "genome size (mb)",
        "SEX": "sex",
        "REFERENCE_GENOME": "reference genome",
        "TISSUE_TYPE": "tissue type",
        "NUCLEIC_ACID_TYPE": "nucleic acid type",
        "NUCLEIC_ACID_SIZE": "nucleic acid size (kb)",
        "BUFFER": "buffer",
        "VOLUME": "volume (ul)",
        "CONCENTRATION": "concentration",
        "CONCENTRATION_UNITS": "concentration units",
        "LIBRARY_SIZE": "library size (bases)",
        "NUMBER_IN_POOL": "number in pool",
        "LIBRARY_TYPE": "library type",
        "LIBRARY_INDEX_SERIES": "library index series",
        "LIBRARY_INDEX_NAME": "library index name",
        "ADAPTER_TYPE": "adapter type",
        "I7_INDEX": "i7 index",
        "I5_INDEX": "i5 index",
        "COMMENTS": "comments"
    },
    "tissueTypeMap": {
        "Breast Tumor (frozen)": "BIOPSY",
        "Buffy Coats": "BUFFY COAT",
        "Cell Culture": "CELLS",
        "Cell Pellet": "CELLS",
        "Crossed-Linked Cell Pellet": "CELLS",
        "Endometrial (FFPE)": "SWAB",
        "Endometrial Lavage": "SWAB",
        "Endometrial Toa Brush": "SWAB",
        "Saliva": "SALIVA",
        "Serum": "PLASMA",
        "Solid Tissue (biopsy) Brain": "BIOPSY",
        "Solid Tissue (biopsy)": "BIOPSY",
        "Whole Blood": "BLOOD"
    },
    "nucleicAcidTypeMap": {
        "Genomic DNA": "DNA",
        "cDNA": "DNA",
        "Amplicons": "DNA",
        "ChIP DNA": "DNA",
        "polyA RNA": "RNA",
        "Total RNA": "RNA",
        "Nuclear RNA": "RNA",
        "Cytoplasmic RNA": "RNA",
        "Small RNA": "RNA"
    },
    "sampleTypes": {
        "TISSUE": "Tissue",
        "NUCLEIC_ACID": "Nucleic Acid",
        "ILLUMINA_LIBRARY": "Illumina Library",
        "ILLUMINA_LIBRARY_POOL": "Illumina Library Pool",
        "LIBRARY_IN_POOL": "Library In Pool",
        "EXISTING_SAMPLE_OR_LIBRARY": "Existing Sample or Library"
    },
    "containerTypes": {
        "WELL_PLATE_96": "96 well plate",
        "WELL_PLATE_384": "384 well plate",
        "TUBE": "Tube"
    },
    "taxonTypeMap": {
        "Eukaryota:Homo sapiens (Taxon ID:9606)": 9606,
        "Eukaryota:Mus musculus (Taxon ID:10090)": 10090,
        "Viruses:Severe acute respiratory syndrome coronavirus 2 (Taxon ID:2697049)": 2697049,
        "NOT_IN_MOH": "Ixodes Scapularis"
    },
    "concentration_units": {
        "NG_UL": "ng/uL"
    },
    "library_types": {
        "PCR_FREE" : "PCR-free",
        "PCR_ENRICHED" : "PCR-enriched",
        "WGBS" : "WGBS",
        "RNA_SEQ" : "RNASeq",
        "ATAC_SEQ" : "ATACSeq",
        "CHIP_SEQ" : "ChIPSeq",
        "G10X_GDNA" : "10x Genomics Linked Reads gDNA",
        "G10X_RNA" : "10x Genomics Single Cell RNA",
        "G10X_CNV" : "10x Genomics Single Cell CNV",
        "G10X_VS_RNA" : "10x Genomics Single Cell Visium Spatial RNA",
        "G10X_BARCODE" : "10x Genomics Single Cell Feature Barcode",
        "G10X_ATAC" : "10x Genomics Single Cell ATAC",
        "G10X_V_D_J" : "10x Genomics Single Cell V-D-J",
        "MCC" : "MCC",
        "EXOME" : "Exome",
        "HIC" : "HiC",
        "HALO_PLEX" : "HaloPlex",
        "PANEL" : "Panel",
        "AMPLICON_DNA" : "Amplicon DNA",
        "AMPLICON_RNA" : "Amplicon RNA"
    }
}