FMConfig = {
    "headers": {
        "SAMPLE_KIND": "Sample Kind",
        "SAMPLE_NAME": "Sample Name",
        "ALIAS": "Alias",
        "PROJECT": "Project",
        "COHORT": "Cohort",
        "EXPERIMENTAL_GROUP": "Experimental Group",
        "TAXON": "NCBI Taxon ID #",
        "SAMPLE_COORD": "Sample Coord",
        "CONTAINER_KIND": "Container Kind",
        "CONTAINER_NAME": "Container Name",
        "CONTAINER_BARCODE": "Container Barcode",
        "LOCATION_BARCODE": "Location Barcode",
        "CONTAINER_COORD": "Container Coord",
        "INDIVIDUAL_ID": "Individual ID",
        "SEX": "Sex",
        "PEDIGREE": "Pedigree",
        "MOTHER_ID": "Mother ID",
        "FATHER_ID": "Father ID",
        "VOLUME": "Volume (uL)",
        "CONCENTRATION": "Conc. (ng/uL)",
        "COLLECTION_SITE": "Collection Site",
        "TISSUE_SOURCE": "Tissue Source",
        "LIBRARY_TYPE": "Library Type",
        "PLATFORM": "Platform",
        "STRANDEDNESS": "Strandedness",
        "INDEX_SET": "Index Set",
        "INDEX": "Index",
        "RECEPTION_DATE": "Reception Date",
        "COMMENT": "Comment"
    },
    "containerKind": {
        "TUBE": "Tube",
        "WELL_PLATE_96": "96-well plate",
        "WELL_PLATE_384": "384-well plate",
        "TUBE_STRIP_2X1": "Tube Strip 2x1",
        "TUBE_STRIP_3X1": "Tube Strip 3x1",
        "TUBE_STRIP_4X1": "Tube Strip 4x1",
        "TUBE_STRIP_5X1": "Tube Strip 5x1",
        "TUBE_STRIP_6X1": "Tube Strip 6x1",
        "TUBE_STRIP_7X1": "Tube Strip 7x1",
        "TUBE_STRIP_8X1": "Tube Strip 8x1"
    },
    "library_types": {
        "PCR_FREE": "PCR-free",
        "PCR_ENRICHED" : "PCR-enriched",
        "RNA_SEQ" : "RNASeq",
        "WGBS" : "WGBS",
        "T_16S" : "16S",
        "T_18S" : "18S",
        "MI_RNA" : "miRNA"
    }
}